From zsh-workers-return-12882-mason-zsh=primenet.com.au@sunsite.auc.dk Wed Oct 04 11:53:20 2000
Return-Path: <zsh-workers-return-12882-mason-zsh=primenet.com.au@sunsite.auc.dk>
Delivered-To: mason-zsh@primenet.com.au
Received: (qmail 20230 invoked from network); 4 Oct 2000 11:53:19 -0000
Received: from sunsite.auc.dk (130.225.51.30)
  by ns1.primenet.com.au with SMTP; 4 Oct 2000 11:53:19 -0000
Received: (qmail 25856 invoked by alias); 4 Oct 2000 11:53:07 -0000
Mailing-List: contact zsh-workers-help@sunsite.auc.dk; run by ezmlm
Precedence: bulk
X-No-Archive: yes
Delivered-To: mailing list zsh-workers@sunsite.auc.dk
X-Seq: 12882
Received: (qmail 25849 invoked from network); 4 Oct 2000 11:53:06 -0000
Date: Wed, 4 Oct 2000 13:53:04 +0200 (MET DST)
Message-Id: <200010041153.NAA09538@beta.informatik.hu-berlin.de>
From: Sven Wischnowsky <wischnow@informatik.hu-berlin.de>
To: zsh-workers@sunsite.auc.dk
In-reply-to: "Bart Schaefer"'s message of Wed, 4 Oct 2000 09:47:34 +0000
Subject: Re: Use of zerr() vs. zwarn()


Bart Schaefer wrote:

> Welcome back, Sven!  Hope you had a good holiday.

Yes, thanks.

> On Oct 4, 11:30am, Sven Wischnowsky wrote:
> }
> } Bart Schaefer wrote:
> } 
> } > On Sep 29,  4:58pm, Bart Schaefer wrote:
> } > }
> } > } init.c:1122:    zwarnnam(name, "option valid only in functions called from completion",
> } > }   Should these use zerrnam(), as do completion-only conditions within
> } > }   [[ ... ]] ?
> } > 
> } > Judging from the indentation on the line following the call to zwarnnam(),
> } > I suspect that this originally *was* a call to zerrnam() and was changed
> } 
> } Yes, please. I changed that in 10131.
> 
> ...??  Not Src/init.c, you didn't.

Sorry, I was confused by the `... from completion'.

> } The discussion leading up to it is in 10120, 10122 and before. We had
> } problems with builtins stopping loops (or not) because of errflag.
> 
> Yes, exactly; that's the same sort of thing I was trying to address with
> the other zerr --> zwarn changes.
> 
> However, "... only in functions called from completion ..." is not an
> error that can possibly occur in any case where a loop *ought* to
> continue, is it?

Right.

Bye
 Sven


--
Sven Wischnowsky                         wischnow@informatik.hu-berlin.de

